fine_label_map = {
    'YSO-1': {'fine_index': 0, 'fine_Text': 'Embedded YSO', 'coarse_index': 0, 'coarse_text': 'YSO-1'},
    'YSO-2': {'fine_index': 1, 'fine_Text': 'YSO', 'coarse_index': 1, 'coarse_text': 'YSO-2'},
    'YSO-3': {'fine_index': 2, 'fine_Text': 'Evolved YSO', 'coarse_index': 2, 'coarse_text': 'YSO'},
    'YSO-4': {'fine_index': 3, 'fine_Text': 'HAeBe YSO', 'coarse_index': 2, 'coarse_text': 'YSO'},
    'HII': {'fine_index': 4, 'fine_Text': 'H II Region', 'coarse_index': 2, 'coarse_text': 'YSO'},
    'O-EAGB': {'fine_index': 5, 'fine_Text': 'Early-type O-rich AGB star', 'coarse_index': 3, 'coarse_text': 'O-Rich Evolved'},
    'O-AGB': {'fine_index': 6, 'fine_Text': 'Oxygen-rich AGB star', 'coarse_index': 3, 'coarse_text': 'O-Rich Evolved'},
    'O-PAGB': {'fine_index': 7, 'fine_Text': 'Oxygen-rich post-AGB star', 'coarse_index': 3, 'coarse_text': 'O-Rich Evolved'},
    'RSG': {'fine_index': 8, 'fine_Text': 'RSG', 'coarse_index': 6, 'coarse_text': 'Star'},
    'O-PN': {'fine_index': 9, 'fine_Text': 'Oxygen-rich PNe', 'coarse_index': 5, 'coarse_text': 'PN'},
    'C-AGB': {'fine_index': 10, 'fine_Text': 'Carbon-rich AGB star', 'coarse_index': 4, 'coarse_text': 'C-Rich Evolved'},
    'C-PAGB': {'fine_index': 11, 'fine_Text': 'Carbon-rich post-AGB star', 'coarse_index': 4, 'coarse_text': 'C-Rich Evolved'},
    'C-PN': {'fine_index': 12, 'fine_Text': 'Carbon-rich PNe', 'coarse_index': 5, 'coarse_text': 'PN'},
    'STAR': {'fine_index': 13, 'fine_Text': 'Stellar photosphere', 'coarse_index': 6, 'coarse_text': 'Star'},
    'STAR: dusty OB star': {'fine_index': 14, 'fine_Text': 'Dusty OB star', 'coarse_index': 6, 'coarse_text': 'Star'},
    'RCrB': {'fine_index': 15, 'fine_Text': 'R CrB star', 'coarse_index': 7, 'coarse_text': 'Other'},
    'BSG': {'fine_index': 16, 'fine_Text': 'Blue supergiant', 'coarse_index': 7, 'coarse_text': 'Other'},
    'WR': {'fine_index': 17, 'fine_Text': 'WR star', 'coarse_index': 7, 'coarse_text': 'Other'},
    'OTHER: B[e] star': {'fine_index': 18, 'fine_Text': 'B[e] star', 'coarse_index': 7, 'coarse_text': 'Other'},
    'OTHER: FG O-EAGB': {'fine_index': 19, 'fine_Text': 'Foreground star', 'coarse_index': 7, 'coarse_text': 'Other'},
    'LBV': {'fine_index': 20, 'fine_Text': 'Luminous Blue Variable', 'coarse_index': 7, 'coarse_text': 'Other'},
    'GAL': {'fine_index': 21, 'fine_Text': 'Galaxy', 'coarse_index': 8, 'coarse_text': 'Galaxy'},
    'UNK': {'fine_index': 22, 'fine_Text': 'Unknown', 'coarse_index': 7, 'coarse_text': 'Other'},
}

coarse_label_map = [
    'YSO-1',
    'YSO-2',
    'YSO',
    'O-Rich Evolved',
    'C-Rich Evolved',
    'PN',
    'Star',
    'Other',
    'Galaxy',
    'Noise',
]
